# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\customer_signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(730, 771)
        Dialog.setMinimumSize(QtCore.QSize(730, 771))
        Dialog.setMaximumSize(QtCore.QSize(771, 771))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../Resources/Icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background: white;")
        self.frm_Signup = QtWidgets.QFrame(Dialog)
        self.frm_Signup.setGeometry(QtCore.QRect(0, 0, 731, 771))
        self.frm_Signup.setStyleSheet("background: #444")
        self.frm_Signup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_Signup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_Signup.setObjectName("frm_Signup")
        self.lbl_Depot = QtWidgets.QLabel(self.frm_Signup)
        self.lbl_Depot.setGeometry(QtCore.QRect(200, 50, 311, 111))
        self.lbl_Depot.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Depot.setStyleSheet("font-family: Calibri Light;\n"
"font-size: 50px;\n"
"font-weight: bold;")
        self.lbl_Depot.setText("")
        self.lbl_Depot.setPixmap(QtGui.QPixmap(".\\../Resources/Icons/depotbigger.png"))
        self.lbl_Depot.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Depot.setObjectName("lbl_Depot")
        self.txt_Pass = QtWidgets.QLineEdit(self.frm_Signup)
        self.txt_Pass.setGeometry(QtCore.QRect(270, 390, 241, 31))
        self.txt_Pass.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txt_Pass.setStyleSheet("border: 2px solid rgb(243, 76, 83);\n"
"border-radius: 15px;\n"
"padding-left: 10px;\n"
"padding-bottom: 1px;\n"
"color: white;\n"
"font-size: 20px;")
        self.txt_Pass.setClearButtonEnabled(True)
        self.txt_Pass.setObjectName("txt_Pass")
        self.txt_SelEmail = QtWidgets.QLineEdit(self.frm_Signup)
        self.txt_SelEmail.setGeometry(QtCore.QRect(270, 310, 241, 31))
        self.txt_SelEmail.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txt_SelEmail.setStyleSheet("border: 2px solid rgb(243, 76, 83);\n"
"border-radius: 15px;\n"
"padding-left: 10px;\n"
"padding-bottom: 1px;\n"
"color: white;\n"
"font-size: 20px;")
        self.txt_SelEmail.setClearButtonEnabled(True)
        self.txt_SelEmail.setObjectName("txt_SelEmail")
        self.lbl_Pass = QtWidgets.QLabel(self.frm_Signup)
        self.lbl_Pass.setGeometry(QtCore.QRect(120, 390, 111, 31))
        self.lbl_Pass.setStyleSheet("color: white;\n"
"font-size: 20px;")
        self.lbl_Pass.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Pass.setObjectName("lbl_Pass")
        self.lbl_Email = QtWidgets.QLabel(self.frm_Signup)
        self.lbl_Email.setGeometry(QtCore.QRect(120, 310, 111, 31))
        self.lbl_Email.setStyleSheet("color: white;\n"
"font-size: 20px;")
        self.lbl_Email.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Email.setObjectName("lbl_Email")
        self.lbl_Fname = QtWidgets.QLabel(self.frm_Signup)
        self.lbl_Fname.setGeometry(QtCore.QRect(110, 230, 121, 31))
        self.lbl_Fname.setStyleSheet("color: white;\n"
"font-size: 20px;")
        self.lbl_Fname.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Fname.setObjectName("lbl_Fname")
        self.lineEdit = QtWidgets.QLineEdit(self.frm_Signup)
        self.lineEdit.setGeometry(QtCore.QRect(270, 230, 241, 31))
        self.lineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit.setStyleSheet("border: 2px solid rgb(243, 76, 83);\n"
"border-radius: 15px;\n"
"padding-left: 10px;\n"
"padding-bottom: 1px;\n"
"color: white;\n"
"font-size: 20px;")
        self.lineEdit.setText("")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.txt_PassConfirm = QtWidgets.QLineEdit(self.frm_Signup)
        self.txt_PassConfirm.setGeometry(QtCore.QRect(270, 470, 241, 31))
        self.txt_PassConfirm.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txt_PassConfirm.setStyleSheet("border: 2px solid rgb(243, 76, 83);\n"
"border-radius: 15px;\n"
"padding-left: 10px;\n"
"padding-bottom: 1px;\n"
"color: white;\n"
"font-size: 20px;")
        self.txt_PassConfirm.setClearButtonEnabled(True)
        self.txt_PassConfirm.setObjectName("txt_PassConfirm")
        self.lbl_PassConfirm = QtWidgets.QLabel(self.frm_Signup)
        self.lbl_PassConfirm.setGeometry(QtCore.QRect(70, 470, 161, 31))
        self.lbl_PassConfirm.setStyleSheet("color: white;\n"
"font-size: 20px;")
        self.lbl_PassConfirm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_PassConfirm.setObjectName("lbl_PassConfirm")
        self.btn_Signup = QtWidgets.QPushButton(self.frm_Signup)
        self.btn_Signup.setGeometry(QtCore.QRect(280, 580, 191, 51))
        self.btn_Signup.setStyleSheet("border: none;\n"
"border-radius: 15px;\n"
"background: rgb(243, 76, 83);\n"
"font-size: 20px;")
        self.btn_Signup.setObjectName("btn_Signup")
        self.btn_Seller = QtWidgets.QPushButton(self.frm_Signup)
        self.btn_Seller.setGeometry(QtCore.QRect(230, 660, 291, 51))
        self.btn_Seller.setStyleSheet("border: none;\n"
"border-radius: 15px;\n"
"background: #222;\n"
"color: white;\n"
"font-size: 20px;\n"
"")
        self.btn_Seller.setObjectName("btn_Seller")

        self.retranslateUi(Dialog)
        self.txt_Pass.returnPressed.connect(self.txt_PassConfirm.setFocus)
        self.txt_PassConfirm.returnPressed.connect(self.btn_Signup.setFocus)
        self.txt_SelEmail.returnPressed.connect(self.txt_Pass.setFocus)
        self.lineEdit.returnPressed.connect(self.txt_SelEmail.setFocus)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Customer Signup"))
        self.lbl_Pass.setText(_translate("Dialog", "Password"))
        self.lbl_Email.setText(_translate("Dialog", "E-Mail"))
        self.lbl_Fname.setText(_translate("Dialog", "Full Name"))
        self.lbl_PassConfirm.setText(_translate("Dialog", "Confirm Password"))
        self.btn_Signup.setText(_translate("Dialog", "Signup"))
        self.btn_Seller.setText(_translate("Dialog", "Sign up as a seller"))
