# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\login_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(401, 561)
        Dialog.setMinimumSize(QtCore.QSize(401, 561))
        Dialog.setMaximumSize(QtCore.QSize(401, 561))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../Resources/Icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 401, 561))
        self.frame.setStyleSheet("background: #444;\n"
"color: white;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lbl_Depot = QtWidgets.QLabel(self.frame)
        self.lbl_Depot.setGeometry(QtCore.QRect(0, 30, 401, 111))
        self.lbl_Depot.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Depot.setStyleSheet("font-family: Calibri Light;\n"
"font-size: 50px;\n"
"font-weight: bold;")
        self.lbl_Depot.setText("")
        self.lbl_Depot.setPixmap(QtGui.QPixmap(".\\../Resources/Icons/depot200.png"))
        self.lbl_Depot.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Depot.setObjectName("lbl_Depot")
        self.txt_Pass = QtWidgets.QLineEdit(self.frame)
        self.txt_Pass.setGeometry(QtCore.QRect(130, 230, 241, 31))
        self.txt_Pass.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txt_Pass.setStyleSheet("border: 2px solid rgb(243, 76, 83);\n"
"border-radius: 15px;\n"
"padding-left: 10px;\n"
"padding-bottom: 1px;\n"
"color: white;\n"
"font-size: 20px;")
        self.txt_Pass.setClearButtonEnabled(True)
        self.txt_Pass.setObjectName("txt_Pass")
        self.txt_Email = QtWidgets.QLineEdit(self.frame)
        self.txt_Email.setGeometry(QtCore.QRect(130, 160, 241, 31))
        self.txt_Email.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txt_Email.setStyleSheet("border: 2px solid rgb(243, 76, 83);\n"
"border-radius: 15px;\n"
"padding-left: 10px;\n"
"padding-bottom: 1px;\n"
"color: white;\n"
"font-size: 20px;")
        self.txt_Email.setClearButtonEnabled(True)
        self.txt_Email.setObjectName("txt_Email")
        self.lbl_Pass = QtWidgets.QLabel(self.frame)
        self.lbl_Pass.setGeometry(QtCore.QRect(10, 230, 101, 31))
        self.lbl_Pass.setStyleSheet("color: white;\n"
"font-size: 20px;")
        self.lbl_Pass.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Pass.setObjectName("lbl_Pass")
        self.lbl_Email = QtWidgets.QLabel(self.frame)
        self.lbl_Email.setGeometry(QtCore.QRect(40, 160, 71, 31))
        self.lbl_Email.setStyleSheet("color: white;\n"
"font-size: 20px;")
        self.lbl_Email.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Email.setObjectName("lbl_Email")
        self.lbl_Alt = QtWidgets.QLabel(self.frame)
        self.lbl_Alt.setGeometry(QtCore.QRect(100, 390, 211, 61))
        self.lbl_Alt.setStyleSheet("color: white;\n"
"font-size: 15px;")
        self.lbl_Alt.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Alt.setObjectName("lbl_Alt")
        self.btn_Signup = QtWidgets.QPushButton(self.frame)
        self.btn_Signup.setGeometry(QtCore.QRect(110, 460, 181, 51))
        self.btn_Signup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Signup.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_Signup.setStyleSheet("border: none;\n"
"border-radius: 15px;\n"
"background: #222;\n"
"color: white;\n"
"font-size: 25px;")
        self.btn_Signup.setObjectName("btn_Signup")
        self.btn_Login = QtWidgets.QPushButton(self.frame)
        self.btn_Login.setGeometry(QtCore.QRect(110, 330, 181, 51))
        self.btn_Login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Login.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_Login.setStyleSheet("background: 2px solid rgb(243, 76, 83);\n"
"border-radius: 15px;\n"
"font-size: 25px;\n"
"")
        self.btn_Login.setCheckable(True)
        self.btn_Login.setObjectName("btn_Login")

        self.retranslateUi(Dialog)
        self.txt_Email.returnPressed.connect(self.txt_Pass.setFocus)
        self.txt_Pass.returnPressed.connect(self.btn_Login.setFocus)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Login"))
        self.lbl_Pass.setText(_translate("Dialog", "Password"))
        self.lbl_Email.setText(_translate("Dialog", "E-Mail"))
        self.lbl_Alt.setText(_translate("Dialog", "Don\'t have an account already?\n"
"Sign up over here!!!"))
        self.btn_Signup.setText(_translate("Dialog", "Sign up"))
        self.btn_Login.setText(_translate("Dialog", "Login"))
