# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sellerwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class SellerGUI(object):

    def __init__(self, conn, MainWindow):
        self.conn = conn
        self.mainform = MainWindow
        self.setupUi(MainWindow)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./Resources/Icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("*{background: rgb(69, 69, 69);\n"
"color: rgb(200, 200, 200);\n"
"font-size: 20px;}\n"
"\n"
"QFrame, QWdiget, QPushButton {border: none;}\n"
"\n"
" ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frm_SellerWindow = QtWidgets.QFrame(self.centralwidget)
        self.frm_SellerWindow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_SellerWindow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_SellerWindow.setObjectName("frm_SellerWindow")
        self.frm_NavBar = QtWidgets.QFrame(self.frm_SellerWindow)
        self.frm_NavBar.setGeometry(QtCore.QRect(382, 0, 1191, 51))
        self.frm_NavBar.setStyleSheet("background: rgb(243, 76, 83);\n"
"color: rgb(69, 69, 69);")
        self.frm_NavBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_NavBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_NavBar.setObjectName("frm_NavBar")
        self.txt_SearchBar = QtWidgets.QLineEdit(self.frm_NavBar)
        self.txt_SearchBar.setGeometry(QtCore.QRect(110, 5, 600, 41))
        self.txt_SearchBar.setStyleSheet("border-radius: 15px;\n"
"padding-left: 10px;\n"
"background: rgb(200, 200, 200);\n"
"")
        self.txt_SearchBar.setObjectName("txt_SearchBar")
        self.pushButton = QtWidgets.QPushButton(self.frm_NavBar)
        self.pushButton.setGeometry(QtCore.QRect(1130, 0, 100, 51))
        self.pushButton.setStyleSheet("border: none;\n"
" background: rgba(0, 0, 0, 0);\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frm_NavBar)
        self.pushButton_2.setGeometry(QtCore.QRect(1250, 0, 100, 51))
        self.pushButton_2.setStyleSheet("border: none;\n"
" background: rgba(0, 0, 0, 0);\n"
"")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.frm_Divider = QtWidgets.QFrame(self.frm_SellerWindow)
        self.frm_Divider.setGeometry(QtCore.QRect(370, 54, 1, 821))
        self.frm_Divider.setStyleSheet("border-radius: 1px;\n"
"background: rgb(200, 200, 200);")
        self.frm_Divider.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_Divider.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_Divider.setObjectName("frm_Divider")
        self.frm_Divider_2 = QtWidgets.QFrame(self.frm_SellerWindow)
        self.frm_Divider_2.setGeometry(QtCore.QRect(40, 130, 300, 1))
        self.frm_Divider_2.setStyleSheet("border-radius: 1px;\n"
"background: rgb(200, 200, 200);")
        self.frm_Divider_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_Divider_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_Divider_2.setObjectName("frm_Divider_2")
        self.frm_Divider_3 = QtWidgets.QFrame(self.frm_SellerWindow)
        self.frm_Divider_3.setGeometry(QtCore.QRect(40, 490, 300, 1))
        self.frm_Divider_3.setStyleSheet("border-radius: 1px;\n"
"background: rgb(200, 200, 200);")
        self.frm_Divider_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_Divider_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_Divider_3.setObjectName("frm_Divider_3")
        self.btn_Accounts = QtWidgets.QPushButton(self.frm_SellerWindow)
        self.btn_Accounts.setGeometry(QtCore.QRect(80, 350, 81, 20))
        self.btn_Accounts.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Accounts.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.btn_Accounts.setStyleSheet("border: none;")
        self.btn_Accounts.setObjectName("btn_Accounts")
        self.btn_Edit = QtWidgets.QPushButton(self.frm_SellerWindow)
        self.btn_Edit.setGeometry(QtCore.QRect(50, 240, 93, 20))
        self.btn_Edit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Edit.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.btn_Edit.setStyleSheet("border: none;")
        self.btn_Edit.setObjectName("btn_Edit")
        self.btn_Home = QtWidgets.QPushButton(self.frm_SellerWindow)
        self.btn_Home.setGeometry(QtCore.QRect(50, 90, 93, 20))
        self.btn_Home.setStyleSheet("border: none;")
        self.btn_Home.setObjectName("btn_Home")
        self.btn_Add = QtWidgets.QPushButton(self.frm_SellerWindow)
        self.btn_Add.setGeometry(QtCore.QRect(50, 200, 93, 20))
        self.btn_Add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Add.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.btn_Add.setStyleSheet("border: none;")
        self.btn_Add.setObjectName("btn_Add")
        self.lbl_Sell = QtWidgets.QLabel(self.frm_SellerWindow)
        self.lbl_Sell.setGeometry(QtCore.QRect(70, 160, 55, 16))
        self.lbl_Sell.setStyleSheet("color: rgb(150, 150, 150);")
        self.lbl_Sell.setObjectName("lbl_Sell")
        self.frm_Divider_4 = QtWidgets.QFrame(self.frm_SellerWindow)
        self.frm_Divider_4.setGeometry(QtCore.QRect(40, 280, 300, 1))
        self.frm_Divider_4.setStyleSheet("border-radius: 1px;\n"
"background: rgb(200, 200, 200);")
        self.frm_Divider_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_Divider_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_Divider_4.setObjectName("frm_Divider_4")
        self.lbl_Sell_2 = QtWidgets.QLabel(self.frm_SellerWindow)
        self.lbl_Sell_2.setGeometry(QtCore.QRect(70, 310, 55, 16))
        self.lbl_Sell_2.setStyleSheet("color: rgb(150, 150, 150);")
        self.lbl_Sell_2.setObjectName("lbl_Sell_2")
        self.btn_BankDetails = QtWidgets.QPushButton(self.frm_SellerWindow)
        self.btn_BankDetails.setGeometry(QtCore.QRect(80, 400, 111, 20))
        self.btn_BankDetails.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_BankDetails.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.btn_BankDetails.setStyleSheet("border: none;")
        self.btn_BankDetails.setObjectName("btn_BankDetails")
        self.btn_Address = QtWidgets.QPushButton(self.frm_SellerWindow)
        self.btn_Address.setGeometry(QtCore.QRect(80, 450, 71, 20))
        self.btn_Address.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Address.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.btn_Address.setStyleSheet("border: none;")
        self.btn_Address.setObjectName("btn_Address")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frm_SellerWindow)
        self.stackedWidget.setGeometry(QtCore.QRect(380, 60, 1191, 821))
        self.stackedWidget.setObjectName("stackedWidget")
        self.Home = QtWidgets.QWidget()
        self.Home.setObjectName("Home")
        self.frm_Home = QtWidgets.QFrame(self.Home)
        self.frm_Home.setGeometry(QtCore.QRect(0, 0, 1191, 811))
        self.frm_Home.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_Home.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_Home.setObjectName("frm_Home")
        self.grp_UpAndRunning = QtWidgets.QGroupBox(self.frm_Home)
        self.grp_UpAndRunning.setGeometry(QtCore.QRect(0, -1, 787, 811))
        self.grp_UpAndRunning.setObjectName("grp_UpAndRunning")
        self.listWidget = QtWidgets.QListWidget(self.grp_UpAndRunning)
        self.listWidget.setGeometry(QtCore.QRect(10, 30, 771, 771))
        self.listWidget.setStyleSheet("")
        self.listWidget.setObjectName("listWidget")
        self.grp_Analytics = QtWidgets.QGroupBox(self.frm_Home)
        self.grp_Analytics.setGeometry(QtCore.QRect(801, 0, 380, 811))
        self.grp_Analytics.setObjectName("grp_Analytics")
        self.stackedWidget.addWidget(self.Home)
        self.Add = QtWidgets.QWidget()
        self.Add.setObjectName("Add")
        self.frm_Add = QtWidgets.QFrame(self.Add)
        self.frm_Add.setGeometry(QtCore.QRect(0, 0, 1191, 811))
        self.frm_Add.setStyleSheet("#frm_Add{ border: 1px solid rgb(200, 200, 200);}")
        self.frm_Add.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_Add.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_Add.setObjectName("frm_Add")
        self.btn_BrowseImage = QtWidgets.QPushButton(self.frm_Add)
        self.btn_BrowseImage.setGeometry(QtCore.QRect(220, 321, 200, 35))
        self.btn_BrowseImage.setStyleSheet("background: rgb(130, 130, 130);\n"
"border-radius: 10px")
        self.btn_BrowseImage.setObjectName("btn_BrowseImage")
        self.lbl_Image_2 = QtWidgets.QLabel(self.frm_Add)
        self.lbl_Image_2.setGeometry(QtCore.QRect(40, 421, 100, 31))
        self.lbl_Image_2.setStyleSheet("border: none;")
        self.lbl_Image_2.setObjectName("lbl_Image_2")
        self.lbl_Image_3 = QtWidgets.QLabel(self.frm_Add)
        self.lbl_Image_3.setGeometry(QtCore.QRect(40, 571, 100, 31))
        self.lbl_Image_3.setStyleSheet("border: none;")
        self.lbl_Image_3.setObjectName("lbl_Image_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frm_Add)
        self.pushButton_4.setGeometry(QtCore.QRect(565, 741, 200, 41))
        self.pushButton_4.setStyleSheet("border-left: 1px solid rgb(243, 76, 83);\n"
" border-radius: 10px;\n"
" background: rgb(130, 130, 130);\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.textEdit = QtWidgets.QTextEdit(self.frm_Add)
        self.textEdit.setGeometry(QtCore.QRect(220, 541, 411, 161))
        self.textEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textEdit.setStyleSheet("border: 2px solid rgb(243, 76, 83);\n"
"border-radius: 20px;\n"
"padding: 10px;\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.lbl_PixMap = QtWidgets.QLabel(self.frm_Add)
        self.lbl_PixMap.setGeometry(QtCore.QRect(220, 116, 200, 200))
        self.lbl_PixMap.setFocusPolicy(QtCore.Qt.TabFocus)
        self.lbl_PixMap.setStyleSheet("border: 2px solid rgb(243, 76, 83);\n"
"border-radius: 15px;")
        self.lbl_PixMap.setText("")
        self.lbl_PixMap.setObjectName("lbl_PixMap")
        self.lineEdit = QtWidgets.QLineEdit(self.frm_Add)
        self.lineEdit.setGeometry(QtCore.QRect(220, 31, 400, 41))
        self.lineEdit.setStyleSheet("border: 2px solid rgb(243, 76, 83);\n"
"border-radius: 20px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;")
        self.lineEdit.setObjectName("lineEdit")
        self.lbl_ProductName = QtWidgets.QLabel(self.frm_Add)
        self.lbl_ProductName.setGeometry(QtCore.QRect(30, 30, 171, 41))
        self.lbl_ProductName.setObjectName("lbl_ProductName")
        self.pushButton_3 = QtWidgets.QPushButton(self.frm_Add)
        self.pushButton_3.setGeometry(QtCore.QRect(368, 741, 200, 41))
        self.pushButton_3.setStyleSheet("border-right: 1px solid rgb(243, 76, 83);\n"
" border-radius: 10px;\n"
" background: rgb(130, 130, 130);\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.lbl_Image = QtWidgets.QLabel(self.frm_Add)
        self.lbl_Image.setGeometry(QtCore.QRect(30, 196, 100, 31))
        self.lbl_Image.setStyleSheet("border: none;")
        self.lbl_Image.setObjectName("lbl_Image")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.frm_Add)
        self.doubleSpinBox.setGeometry(QtCore.QRect(220, 411, 151, 43))
        self.doubleSpinBox.setStyleSheet("border: 2px solid rgb(243, 76, 83);\n"
"border-radius: 20px;\n"
"padding: 2px;")
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox.setMaximum(1000000.0)
        self.doubleSpinBox.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.stackedWidget.addWidget(self.Add)
        self.pg_Accounts = QtWidgets.QWidget()
        self.pg_Accounts.setObjectName("pg_Accounts")
        self.stackedWidget.addWidget(self.pg_Accounts)
        self.pg_BankDetails = QtWidgets.QWidget()
        self.pg_BankDetails.setObjectName("pg_BankDetails")
        self.stackedWidget.addWidget(self.pg_BankDetails)
        self.gridLayout.addWidget(self.frm_SellerWindow, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.btn_BrowseImage.clicked.connect(self.doubleSpinBox.setFocus)
        self.lineEdit.returnPressed.connect(self.btn_BrowseImage.setFocus)
        self.btn_Add.clicked.connect(self.lineEdit.setFocus)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "depot"))
        self.txt_SearchBar.setPlaceholderText(_translate("MainWindow", "Search"))
        self.btn_Accounts.setText(_translate("MainWindow", "Accounts"))
        self.btn_Edit.setText(_translate("MainWindow", "Edit"))
        self.btn_Home.setText(_translate("MainWindow", "Home"))
        self.btn_Add.setText(_translate("MainWindow", "Add"))
        self.lbl_Sell.setText(_translate("MainWindow", "Sell"))
        self.lbl_Sell_2.setText(_translate("MainWindow", "Seller"))
        self.btn_BankDetails.setText(_translate("MainWindow", "Bank Details"))
        self.btn_Address.setText(_translate("MainWindow", "Address"))
        self.grp_UpAndRunning.setTitle(_translate("MainWindow", "Up and Running"))
        self.grp_Analytics.setTitle(_translate("MainWindow", "Analytics"))
        self.btn_BrowseImage.setText(_translate("MainWindow", "Browse Image"))
        self.lbl_Image_2.setToolTip(_translate("MainWindow", "Add an Image to Accentuate your product"))
        self.lbl_Image_2.setText(_translate("MainWindow", "Cost"))
        self.lbl_Image_3.setToolTip(_translate("MainWindow", "Add an Image to Accentuate your product"))
        self.lbl_Image_3.setText(_translate("MainWindow", "Description"))
        self.pushButton_4.setText(_translate("MainWindow", "Clear"))
        self.lbl_ProductName.setText(_translate("MainWindow", "Product Name"))
        self.pushButton_3.setText(_translate("MainWindow", "OK"))
        self.lbl_Image.setToolTip(_translate("MainWindow", "Add an Image to Accentuate your product"))
        self.lbl_Image.setText(_translate("MainWindow", "Image"))
        self.doubleSpinBox.setPrefix(_translate("MainWindow", "Rs. "))
        self.doubleSpinBox.setSuffix(_translate("MainWindow", "/-"))
